//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public Dish()
        {
            this.DishIngredientLists = new HashSet<DishIngredientList>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> IdType { get; set; }
    
        public virtual TypeOfDish TypeOfDish { get; set; }
        public virtual ICollection<DishIngredientList> DishIngredientLists { get; set; }
    }
}
